---
packages:
  present:
    - git
    - fish
    - blender
    - inkscape
    - retroarch
    - telegram-desktop
    - steam
    - ansible
    - docker
    - git
    - wget
    - pulseaudio-bluetooth
    - slack-online
  absent:
    - palemoon

dirs:
  - aur
  - projects
  - books
  - AppImages

repos:
  - repo: git@github.com:Jerksen/dots.git
    name: dots
  - repo: git@github.com:Jerksen/qmk_firmware.git
    name: qmk_firmware

configs:
  files:
    - .bashrc
    - .vimrc
    - .ansible.cfg
  dirs:
    - .config
    - .i3
    - .ansible

user: jeff
