---
packages:
  present:
    - git
    - fish
    - blender
    - inkscape
    - retroarch
    - telegram-desktop
    - steam-manjaro
    - steam-native
    - docker
    - wget
    - pulseaudio-bluetooth
    - slack-online
    - openssh
    - hplip
  absent:
    - palemoon

dirs:
  - aur
  - projects
  - AppImages

repos:
  - repo: git@github.com:Jerksen/qmk_firmware.git
    name: qmk_firmware
  - repo: git@github.com:Jerksen/openscad
    name: openscad

configs:
  files:
    - .bashrc
    - .vimrc
    - .ansible.cfg
  dirs:
    - .config
    - .i3
    - .ansible

nfsshares:
  - name: home-backup
    src: 192.168.1.105:/volume1/homes/{{ user }}
    dst: /home/{{ user }}/backup

user: jeff
