---
- name: install ssh server
  package:
    name: openssh
    state: present
  tags:
    - access

- name: config ssh server
  service:
    name: sshd
    enabled: yes
  tags:
    - access

# TODO: add printers automagically using hp-setup
# TODO: make sure hplip is installed
# until this hplip stuff is done, make sure you run "sudo pacman -S hplip" or equivalent and then run hp-setup to detect the network printer

- name: create directories
  file:
    path: "{{ item.dst }}"
    state: directory
    mode: 0666
  with_items: "{{ nfsshares }}"
  become: yes
  tags:
    -nfs
    -backup

- name: mount stuff
  mount:
    path: "{{ item.dst }}"
    src: "{{ item.src }}"
    opts: hard
    fstype: nfs
    state: present
  with_items: "{{ nfsshares }}"
  become: yes
  tags:
    - nfs
    - backup
...
