---
- name: create home directories
  file:
    path: /home/{{ user }}/{{ item }}
    state: directory
    owner: "{{ user }}"
  with_items: "{{ dirs }}"

- name: install packages
  pacman:
    name: "{{ packages.present }}"
    state: present
  become: yes
  tags:
    - pacman

- name: remove packages
  pacman:
    name: "{{ packages.absent }}"
    state: absent
  become: yes
  tags:
    - pacman

- name: update system
  pacman:
    upgrade: yes
  become: yes

- name: test for fish already set
  shell: grep "bin/fish" /etc/shells
  register: fishinshell

- name: add fish to the list of shells
  lineinfile:
    path: /etc/shells
    line: '/usr/bin/fish'
  when: fishinshell.stdout != ""
  tags:
    - shell

- name: set fish to be default shell
  user:
    name: "{{ user }}"
    shell: /usr/bin/fish

- name: clone git repos
  git:
    repo: "{{ item.repo }}"
    dest: /home/{{ user }}/{{ item.name }}
  become_user: "{{ user }}"
  with_items: "{{ repos }}"
  tags:
    - git

- name: pamac install arduino
  command: pamac install --no-confirm arduino arduino-docs
  tags:
    - pamac

- name: pamac install 3d tools
  command: pamac install --no-confirm openscad cura 
  tags:
    - pamac
    - STL

- name: distribute config files
  copy:
    src: "{{ item }}"
    dest: /home/{{ user }}/{{ item }}
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items: "{{ configs.files }}"
  tags:
    - config

- name: distribute config directories
  copy:
    src: "{{ item }}"
    dest: /home/{{ user }}
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items: "{{ configs.dirs }}"
  tags:
    - config
...
